service: backend-kloaka

frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  websocketsApiRouteSelectionExpression: $request.body.action


  environment:
    TableA: Kloaka-Zone-A
    TableB: Kloaka-Zone-B
    TableC: Kloaka-Zone-C
    ProblemTable: Kloaka-Problem
    WebsocketManager: Kloaka-WebsocketManager

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:us-east-1:815814454771:table/*"
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
            - "execute-api:Invoke"
          Resource:
            - "arn:aws:execute-api:*:*:*"
#        - Effect: Allow
#          Action:
#            - "iot:Publish"
#          Resource:
#            - "arn:aws:iot:us-east-1:815814454771:*"

functions:
  organizer:
    handler: src/organizer.handler
    events:
      - iot:
          name: "kloaka_organizer"
          description: "KLOAKA - Message organizer and formatter. This rule gets messages posted on 'from_device' topic and put them in the relative zone DynamoDB Table"
          sql: "SELECT end_device_ids.device_id as id, end_device_ids.dev_eui as dev_eui, uplink_message.frm_payload as filling FROM 'thethings/lorawan/kloaka-ttn/#'"

  getDeviceStat:
    handler: src/rest.getDeviceStat
    events:
      - httpApi:
          path: /device/{id}
          method: get
          cors: true

  getAllDevices:
    handler: src/rest.getAllDevices
    events:
      - httpApi:
          path: /device/scan
          method: get
          cors: true

  getProblem:
    handler: src/rest.getProblem
    events:
      - httpApi:
          path: /problem/{problem_id}
          method: get
          cors: true
          
  getAllProblems:
    handler: src/rest.getAllProblems
    events:
      - httpApi:
          path: /problem/scan
          method: get
          cors: true

  triggerComparator:
    handler: src/problem.trigger
    events:
      - stream: arn:aws:dynamodb:us-east-1:815814454771:table/Kloaka-Zone-A/stream/2021-05-17T09:20:04.167
  
  connect:
    handler: src/websocket.connect
    events:
      - websocket:
          route: $connect
          cors: true

  disconnect:
    handler: src/websocket.disconnect
    events:
      - websocket:
          route: $disconnect
          cors: true

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello
